# Site settings
title: Le Zeng's Blog
email: zenglekidd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Le Zeng's personal blog talks about iOS, Tech, Hardware and Travel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zenglekidd
github_username:  zenglekidd

# Build settings
markdown: kramdown
